version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w9x4f4k1
  build:
    commands:
      - echo Building the Docker image...
      - docker build -f Source/docker/Dockerfile -t pacman_project .
      - docker tag pacman_project:latest public.ecr.aws/w9x4f4k1/pacman_project:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push public.ecr.aws/w9x4f4k1/pacman_project:latest
