version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
  pre_build:
    commands:
      - echo Logging in to Amazon EKS...
      - aws eks update-kubeconfig --region us-west-2 --name PacMan-Cluster
  build:
    commands:
      - echo Applying Kubernetes manifests...
      - kubectl apply -f Kubernetes-Manifests/Secrets/mongodb-secrets.yaml --validate=false
      - kubectl apply -f Kubernetes-Manifests/Configmaps/mongodb-configmap.yaml --validate=false
      - kubectl apply -f Kubernetes-Manifests/Storage-Classes/gp2-storage-class.yaml --validate=false
      - kubectl apply -f Kubernetes-Manifests/Service-Accounts/ebs-csi-controller-sa.yaml --validate=false
      - kubectl apply -f Kubernetes-Manifests/Deployments/mongodb-deployment.yaml --validate=false
      - kubectl apply -f Kubernetes-Manifests/Services/mongodb-service.yaml --validate=false
      - kubectl apply -f Kubernetes-Manifests/Deployments/pacman-deployment.yaml --validate=false
      - kubectl apply -f Kubernetes-Manifests/Services/pacman-service.yaml --validate=false
  post_build:
    commands:
      - echo Deployment completed successfully!