version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
  pre_build:
    commands:
      - echo Logging in to Amazon EKS..
      - aws eks update-kubeconfig --region us-west-2 --name PacMan-Cluster
  build:
    commands:
      - echo Applying Kubernetes manifests...
      - kubectl apply -f Secrets/mongodb-secrets.yaml
      - kubectl apply -f Configmaps/mongodb-configmap.yaml
      - kubectl apply -f Storage-Classes/gp2-storage-class.yaml
      - kubectl apply -f Service-Accounts/ebs-csi-controller-sa.yaml
      - kubectl apply -f Deployments/mongodb-deployment.yaml
      - kubectl apply -f Services/mongodb-service.yaml
      - kubectl apply -f Deployments/pacman-deployment.yaml
      - kubectl apply -f Services/pacman-service.yaml
  post_build:
    commands:
      - echo Deployment completed successfully!