apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pacman-app
  template:
    metadata:
      labels:
        app: pacman-app
    spec:
      containers:
        - name: pacman-app-container
          image: public.ecr.aws/w9x4f4k1/pacman_project:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "DEV"
