apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
        - name: pacman
          image: 891377313726.dkr.ecr.us-west-2.amazonaws.com/pacman-repo/pacman:latest   # Check option for automize
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL  # WORK ON THAT
              value: "mongodb://admin:password@mongodb-service:27017"  # WORK ON THAT

