apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
        - name: pacman
          image: your-docker-repo/pacman:latest   # WORK ON THAT  
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL  # WORK ON THAT
              value: "mongodb://admin:password123@mongodb-service:27017"  # WORK ON THAT
