apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: admin #Encrypt by using: echo -n 'admin' | base64
  mongo-root-password: password #Encrypt by using: echo -n 'password' | base64
