apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: #Encrypt by using: echo -n 'admin' | base64
  mongo-root-password: #Encrypt by using: echo -n 'password' | base64
