apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4= # Base64 encoded of (admin)
  mongo-root-password: cGFzc3dvcmQ= # Base64 encoded of (password)
  mongo-url: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGItc2VydmljZToyNzAxNw== # Base64 encoded of (mongodb://admin:password@mongodb-service:27017)
